### ISSUE TITLE
Fejl på domæneregistreringsside

### ISSUE THREAD

**Issue by josmad** [Edelskjold/HostingGroup-issues-public#2]
Hvis man ikke udfylder `Region` under oprettelse af domæne og trykker videre så sker følgende:

![domæne_fejl](http://puu.sh/ksIBY/52ab3500bd.png)

Siden genindlæser ikke og der kommer ikke nogen rød bar oppe i toppen, som viser hvilke felter der mangler at blive udfyldt.
Knappen fungerer stadig, men det samme bliver ved med at ske så længe `Region` ikke er udfyldt.

**Comment by sebastiannyholm** [comment]
Denne fejl sker fordi feltet for Region får tilføjet attribute'en required, hvilket gør at HTML 5 fortæller at det skal udfyldes. Hvis denne attribute ikke kommer på, ville det virke, også advarslen bagefter om at Region ikke er udfyldt.

**Comment by sebastiannyholm** [comment]
Attribute'en required er nu blevet fjernet og det virker som det skal.
